// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/openclaw-chat/Chat.tsx": () => import("../components/mockups/openclaw-chat/Chat.tsx")
};
